# Generated by Django 4.0.4 on 2022-05-26 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=20, verbose_name='Логин')),
                ('password', models.CharField(max_length=32, verbose_name='Пароль')),
                ('human_name', models.CharField(max_length=32, verbose_name='Имя')),
                ('human_family', models.CharField(max_length=32, verbose_name='Фамилия')),
                ('human_otchestvo', models.CharField(max_length=32, verbose_name='Отчество')),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Учетные записи',
                'verbose_name_plural': 'Учетные записи',
            },
        ),
    ]
