# Generated by Django 4.0.4 on 2022-05-20 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parsing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chanel',
            name='NameChanel',
            field=models.CharField(default=1, max_length=20, verbose_name='Название канала'),
            preserve_default=False,
        ),
    ]
